### ISSUE TITLE
主机管理，添加主机后，在浏览器控制台可以明文查看

### ISSUE THREAD

**Issue by TaoYun-Site** [DTStack/doraemon#14]
主机管理，添加主机后，在浏览器控制台可以明文查看，建议将这个加密
![image](https://user-images.githubusercontent.com/32122326/133539922-9ba80cbc-1ffc-4bdb-a720-d114df6807e1.png)

**Comment by liuxy0551** [comment]
内部使用的系统，主要目的就是公开密码，方便其他开发复制使用。专用性的服务器不建议再此处记录用户名密码
